---
- name: install kcptun (native)
  include_tasks: native.yml

- name: create config folder
  file:
    path: "{{ kcptun_config_path }}"
    state: directory

- name: config kcptun
  copy:
    dest: "{{ kcptun_config_path }}/{{ kcptun_service_name }}.json"
    content: "{{ kcptun_config | to_nice_json }}"
  notify: restart kcptun service
