- name: check kcptun
  command: "{{ kcptun_install_path }}/{{ kcptun_cmd }} -version"
  register: check_version
  changed_when: no
  ignore_errors: yes

- name: force install kcptun if version do not match
  set_fact:
    kcptun_install: true
  when: check_version is failed or check_version.stdout is not search(kcptun_version)

- name: install kcptun
  block:
    - name: kcptun path folder
      file:
        path: "{{ kcptun_install_path }}"
        state: directory

    - name: download kcptun package
      get_url:
        url: "{{ kcptun_download_url }}"
        dest: /tmp/kcptun_package.tar.gz

    - name: unarchive
      unarchive:
        dest: "{{ kcptun_install_path }}"
        src: /tmp/kcptun_package.tar.gz
        remote_src: yes
  when: kcptun_install | default(false) | bool

- name: setup service
  import_role:
    name: 0x0i.systemd
  vars:
    unit_config: "{{ kcptun_service_unit }}"

- name: enable and start kcptun server
  service:
    name: "{{ kcptun_service_name }}"
    enabled: yes
    state: started
