- name: check kcptun
  command: "{{ kcptun_install_path }}/{{ kcptun_server_cmd }} -version"
  register: check_version
  changed_when: no
  ignore_errors: yes

- name: force install kcptun if version do not match
  set_fact:
    kcptun_install: true
  when: check_version is failed or check_version.stdout is not search(kcptun_version)

- name: install kcptun
  block:
    - name: kcptun path folder
      file:
        path: "{{ kcptun_install_path }}"
        state: directory

    - name: download kcptun package
      get_url:
        url: "{{ kcptun_download_url }}"
        dest: /tmp/kcptun_package.tar.gz

    - name: unarchive
      unarchive:
        dest: "{{ kcptun_install_path }}"
        src: /tmp/kcptun_package.tar.gz
        remote_src: yes
  when: kcptun_install | default(false) | bool

- name: setup kcptun server
  block:
    - name: setup service
      include_role:
        name: 0x0i.systemd
      vars:
        unit_config:
          - name: "{{ kcptun_server_name }}"
            Unit:
              Description: kcptun server
              Wants: network.target
              After: syslog.target network-online.target
            Service:
              Type: simple
              ExecStart: "{{ kcptun_install_path }}/{{ kcptun_server_cmd }} -c {{ kcptun_config_path }}/{{ kcptun_server_name }}.json"
              Restart: on-failure
              RestartSec: 10
              KillMode: process
              LimitNOFILE: 65535
            Install:
              WantedBy: multi-user.target
    - name: enable and start kcptun server
      service:
        name: "{{ kcptun_server_name }}"
        enabled: yes
        state: started
  when: kcptun_server_config is defined

- name: setup kcptun client
  block:
    - name: setup kcptun client
      include_role:
        name: 0x0i.systemd
      vars:
        unit_config:
          - name: "{{ kcptun_client_name }}"
            Unit:
              Description: kcptun client
              Wants: network.target
              After: syslog.target network-online.target
            Service:
              Type: simple
              ExecStart: "{{ kcptun_install_path }}/{{ kcptun_client_cmd }} -c {{ kcptun_config_path }}/{{ kcptun_client_name }}.json"
              Restart: on-failure
              RestartSec: 10
              KillMode: process
              LimitNOFILE: 65535
            Install:
              WantedBy: multi-user.target
    - name: enable and start kcptun client
      service:
        name: "{{ kcptun_client_name }}"
        enabled: yes
        state: started
  when: kcptun_client_config is defined
